SELECT DATE_SALES, PRODUCT_NAME, LAST_VALUE(PRICE)
                        OVER (PARTITION BY DATE_SALES ORDER BY PRICE DESC RANGE BETWEEN
                        UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS PRICE
FROM SALES
WHERE STORE_ID = 1
ORDER BY DATE_SALES;

select DISTINCT PRODUCT_NAME, PRICE,
       DENSE_RANK() OVER (ORDER BY PRICE) AS RANG
  from SALES
 ORDER BY RANG;


select DISTINCT PRODUCT_NAME, PRICE,
       RANK() OVER (ORDER BY PRICE) AS RANG
  from SALES
 ORDER BY RANG;
 
select count(*)  as count from (
SELECT DISTINCT PRODUCT_NAME, last_VALUE(PRICE)
                        OVER (ORDER BY PRICE ASC RANGE BETWEEN
                        UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS PRICE
FROM SALES
ORDER BY product_name);



SELECT PRODUCT_ID, PRODUCT_NAME, PRICE, ROW_NUMBER() over (ORDER BY PRICE ASC) AS ord_num
FROM SALES
 
 SELECT distinct product_name, price,
AVG(price)
OVER (ORDER BY price ASC RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) avg_sal
FROM SALES
order by price; 

 SELECT distinct product_name, price,
MAX(price)
OVER (ORDER BY price ASC RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) max_sal
FROM SALES
order by price; 

 SELECT distinct product_name, price,
MIN(price)
OVER (ORDER BY price ASC RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) min_sal
FROM SALES
order by price; 

 SELECT distinct country, city, store_id,
SUM(price)
OVER (PARTITION BY STORE_ID ORDER BY price ASC RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) sum_sal_in_store
FROM SALES;
SELECT COUNT(*) FROM SALES
WHERE PRODUCT_NAME LIKE '%DECO' AND store_id = 1

SELECT * FROM SALES