DROP TABLESPACE ts_SA_DIM_PROD_01 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
CREATE TABLESPACE ts_SA_DIM_PROD_01
DATAFILE '/oracle/u02/oradata/NMartinovichdb/db_qpt_sa_dim_prod_01.dat'
SIZE 150M reuse
 AUTOEXTEND ON NEXT 10M
 SEGMENT SPACE MANAGEMENT AUTO;
 
DROP TABLE DM_PRODUCT;
CREATE TABLE DM_PRODUCT(
PRODUCT_ID NUMBER,
PRODUCT_NAME VARCHAR(30),
COLOR VARCHAR(20),
PRICE NUMBER
) TABLESPACE ts_SA_DIM_PROD_01;

CREATE TABLESPACE ts_SA_DIM_STORE_01
DATAFILE '/oracle/u02/oradata/NMartinovichdb/db_qpt_sa_dim_store_01.dat'
SIZE 150M reuse
 AUTOEXTEND ON NEXT 10M
 SEGMENT SPACE MANAGEMENT AUTO;

DROP TABLE DM_STORES;
CREATE TABLE DM_STORES(
STORE_ID NUMBER,
PHONE VARCHAR(20),
ADDRESS VARCHAR(30),
CITY VARCHAR(30),
COUNTRY VARCHAR(20)
) TABLESPACE ts_SA_DIM_STORE_01;

INSERT INTO DM_PRODUCT VALUES(1, 'Watch Finift', 'WHITE', 169);
INSERT INTO DM_PRODUCT VALUES(2, 'Watch Finift 2', 'GOLD', 169);
INSERT INTO DM_PRODUCT VALUES(3, 'Watch Finift 3', 'BLACH', 169);
INSERT INTO DM_PRODUCT VALUES(4, 'Watch Finift 4', 'BLACK', 169);
INSERT INTO DM_PRODUCT VALUES(5, 'Watch Stones', 'BLUE', 159);
INSERT INTO DM_PRODUCT VALUES(6, 'Watch Stones 2', 'RED', 159);
INSERT INTO DM_PRODUCT VALUES(7, 'Watch Stones 3', 'GOLD', 159);
INSERT INTO DM_PRODUCT VALUES(8, 'Watch Stones 4', 'YELLOW', 159);
INSERT INTO DM_PRODUCT VALUES(9, 'Watch Colors of Armenia', 'YELLOW', 399);
INSERT INTO DM_PRODUCT VALUES(10, 'Watch Colors of Armenia 2', 'BLACK', 399);
INSERT INTO DM_PRODUCT VALUES(11, 'Watch Colors of Armenia 3', 'GREEN', 399);
INSERT INTO DM_PRODUCT VALUES(12, 'Watch Colors of Armenia 4', 'RED', 129);
INSERT INTO DM_PRODUCT VALUES(13, 'Watch DECO', 'BLACK', 129);
INSERT INTO DM_PRODUCT VALUES(14, 'Watch DECO 2', 'BLACK', 129);
INSERT INTO DM_PRODUCT VALUES(15, 'Watch Sirius', 'BLACK', 1999);
INSERT INTO DM_PRODUCT VALUES(16, 'Watch Sirius 2', 'BROWN', 1999);
INSERT INTO DM_PRODUCT VALUES(17, 'Watch Sirius 3', 'RED', 1999);
INSERT INTO DM_PRODUCT VALUES(18, 'Watch Spirit', 'BLACK', 369);
INSERT INTO DM_PRODUCT VALUES(19, 'Watch Spirit 2', 'ORANGE', 369);
INSERT INTO DM_PRODUCT VALUES(20, 'Watch Spirit 3', 'BROWN', 369);
INSERT INTO DM_PRODUCT VALUES(21, 'Watch Spirit 4', 'WHITE', 369);

select * from dm_product;


INSERT INTO DM_STORES VALUES(1, +375294344854, 'Nezavisimosty, 18', 'Minsk', 'BLR');
INSERT INTO DM_STORES VALUES(2, +375294235831, 'Nezavisimosty, 95', 'Minsk', 'BLR');
INSERT INTO DM_STORES VALUES(3, +375294257649, 'National airport', 'Minsk', 'BLR');
INSERT INTO DM_STORES VALUES(4, +375293422332, 'National airport', 'Minsk', 'BLR');
INSERT INTO DM_STORES VALUES(5, +37533424339, 'Sovetskaya, 80 ', 'Brest', 'BLR');
INSERT INTO DM_STORES VALUES(6, +375447031325, 'Lenina, 26 ', 'Vitebsk', 'BLR');
INSERT INTO DM_STORES VALUES(7, +375445128063, 'Pravda, 3A ', 'Gomel', 'BLR');
INSERT INTO DM_STORES VALUES(8, +375336044338, 'Sovetskaya, 6 ', 'Grodno', 'BLR');
INSERT INTO DM_STORES VALUES(9, +375445104794, 'Dubko, 17 ', 'Grodno', 'BLR');
INSERT INTO DM_STORES VALUES(10, +375336335260, 'Sovetskaya, 70 ', 'Bobruisk', 'BLR');
INSERT INTO DM_STORES VALUES(11, +79055309559, 'MKAD 32KM', 'Moscow', 'RUS');
INSERT INTO DM_STORES VALUES(12, +79055309559, 'Energetikov Avenue, 3B', 'Saint-Petersburg', 'RUS');

select * from dm_stores;



DROP table SALES;
CREATE TABLE SALES
 AS(
select a.DATE_Sales, dm_product.product_id, dm_product.product_name,
dm_product.price, dm_stores.store_id, 
dm_stores.city, dm_stores.country
FROM (select b.* ,TRUNC(DBMS_RANDOM.VALUE( 1,22)) as PRODUCT, TRUNC(DBMS_RANDOM.VALUE( 1,13)) as STORES
FROM
(SELECT TRUNC (TO_DATE( '01/08/2022', 'DD/MM/YYYY')+
TRUNC(DBMS_RANDOM.VALUE( 1, (to_date('31/08/2022', 'DD/MM/YYYY') 
-to_date('01/08/2022', 'DD/MM/YYYY')+1)))) DATE_Sales, 
rownum as rn FROM dual CONNECT BY level <= 300 )b 
)a 
LEFT JOIN DM_PRODUCT on PRODUCT = DM_PRODUCT.PRODUCT_ID
LEFT JOIN DM_STORES on STORES = DM_STORES.STORE_ID);

SELECT * FROM SALES
ORDER BY 1, 5
 
Select count(*) FROM SALES

