--Range Partition
CREATE TABLE PRODUCTS
(
    product_id NUMBER(10),
    product_type VARCHAR(40),
    color VARCHAR(40),
    cost NUMBER(10)
)
PARTITION BY RANGE(cost)
(
    PARTITION cheaply_products VALUES LESS THAN (500),
    PARTITION expensive_products VALUES LESS THAN (5000)
)
TABLESPACE TS_REFERENCES_EXT_DATA_01;

ALTER TABLE PRODUCTS
MERGE PARTITIONS cheaply_products, expensive_products INTO PARTITION ALL_PRODUCTS;

ALTER TABLE PRODUCTS MOVE PARTITION ALL_PRODUCTS
TABLESPACE TS_REFERENCES_EXT_DATA_01 NOLOGGING COMPRESS;

ALTER TABLE PRODUCTS SPLIT PARTITION ALL_PRODUCTS
AT (40) INTO (PARTITION cheaply_products, PARTITION expensive_products);

ALTER TABLE PRODUCTS TRUNCATE PARTITION cheaply_products;

ALTER TABLE PRODUCTS drop PARTITION cheaply_products;


ALTER TABLE PRODUCTS 
ADD PARTITION cheaply_products VALUES LESS THAN (5001)
TABLESPACE TS_REFERENCES_EXT_DATA_01;

DROP TABLE PRODUCTS;

--list partition
CREATE TABLE PRODUCTS
(
    product_id NUMBER(10),
    product_type VARCHAR(40),
    color VARCHAR(40),
    cost NUMBER(10)
)
PARTITION BY LIST(color)
(
    PARTITION light_products VALUES ('WHITE', 'GRAY', 'RED'),
    PARTITION black_products VALUES ('BLACK', 'BLUE')
)
TABLESPACE TS_REFERENCES_EXT_DATA_01;

ALTER TABLE PRODUCTS
MERGE PARTITIONS light_products, black_products 
INTO PARTITION ALL_PRODUCTS;

ALTER TABLE PRODUCTS MOVE PARTITION ALL_PRODUCTS
TABLESPACE TS_REFERENCES_EXT_DATA_01 NOLOGGING COMPRESS;

ALTER TABLE PRODUCTS SPLIT PARTITION ALL_PRODUCTS
VALUES ('RED', 'BLUE') 
INTO (PARTITION color_product1, PARTITION color_product2);

ALTER TABLE PRODUCTS TRUNCATE PARTITION color_product1;

ALTER TABLE PRODUCTS drop PARTITION color_product2;

DROP TABLE PRODUCTS;

--hash partition
CREATE TABLE PRODUCTS
(
    product_id NUMBER(10),
    product_type VARCHAR(40),
    color VARCHAR(40),
    cost NUMBER(10)
)
PARTITION BY HASH(cost)
(
    PARTITION Part_1 TABLESPACE TS_REFERENCES_DATA_01,
    PARTITION Part_2 TABLESPACE TS_REFERENCES_EXT_DATA_01
);

INSERT INTO PRODUCTS VALUES (1, 'CLOCK', 'GRAY', 500);
INSERT INTO PRODUCTS VALUES (2, 'CLOCK', 'BLUE', 5000);
INSERT INTO PRODUCTS VALUES (3, 'CLOCK', 'WHITE', 50);
INSERT INTO PRODUCTS VALUES (4, 'CLOCK', 'BLACK', 100);
INSERT INTO PRODUCTS VALUES (5, 'CLOCK', 'GRAY', 4000);
commit;

SELECT * FROM products PARTITION(Part_1);
SELECT * FROM products PARTITION(Part_2);

ALTER TABLE PRODUCTS
ADD PARTITION Part_3
TABLESPACE TS_REFERENCES_EXT_DATA_01;

SELECT * FROM products PARTITION(Part_1);

DROP TABLE PRODUCTS;

