--Storage Level tablespaces

Create TABLESPACE ts_sa_customers_data_01
DATAFILE '/oracle/u02/oradata/NMartinovichdb/db_qpt_sa_customer_data_01.dat'
SIZE 150M reuse
 AUTOEXTEND ON NEXT 50M
 SEGMENT SPACE MANAGEMENT AUTO;
 
 Create TABLESPACE ts_sa_employees_data_01
DATAFILE '/oracle/u02/oradata/NMartinovichdb/db_qpt_sa_employees_data_01.dat'
SIZE 150M reuse
 AUTOEXTEND ON NEXT 50M
 SEGMENT SPACE MANAGEMENT AUTO;
 
 Create TABLESPACE ts_sa_products_data_01
DATAFILE '/oracle/u02/oradata/NMartinovichdb/db_qpt_sa_products_data_01.dat'
SIZE 150M reuse
 AUTOEXTEND ON NEXT 50M
 SEGMENT SPACE MANAGEMENT AUTO;
 
 --Storage Level users
CREATE USER SA_CUSTOMERS 
IDENTIFIED BY "%PWD%" 
DEFAULT TABLESPACE ts_sa_customer_data_01;
GRANT CONNECT,RESOURCE TO SA_CUSTOMERS;

CREATE USER SA_EMPLOYEES
IDENTIFIED BY "%PWD%" 
DEFAULT TABLESPACE ts_sa_employees_data_01;
GRANT CONNECT,RESOURCE TO SA_EMPLOYEES;

CREATE USER SA_PRODUCTS
IDENTIFIED BY "%PWD%" 
DEFAULT TABLESPACE ts_sa_products_data_01;
GRANT CONNECT,RESOURCE TO SA_PRODUCTS;

--DWH Cleansing Level tablespace

Create TABLESPACE ts_dw_cl_01
DATAFILE '/oracle/u02/oradata/NMartinovichdb/db_qpt_dw_cl_01.dat'
SIZE 150M reuse
 AUTOEXTEND ON NEXT 50M
 SEGMENT SPACE MANAGEMENT AUTO;
 
 --DWH Cleansing Level user
 
 CREATE USER DW_CL
IDENTIFIED BY "%PWD%" 
DEFAULT TABLESPACE ts_dw_cl_01;
GRANT CONNECT,CREATE VIEW,RESOURCE TO DW_CL;

--DWH LEVEL tablespace

Create TABLESPACE ts_dw_data_01
DATAFILE '/oracle/u02/oradata/NMartinovichdb/db_qpt_dw_data_01.dat'
SIZE 150M reuse
 AUTOEXTEND ON NEXT 50M
 SEGMENT SPACE MANAGEMENT AUTO;
 
--DWH LEVEL user

 CREATE USER DW_DATA
IDENTIFIED BY "%PWD%" 
DEFAULT TABLESPACE ts_dw_data_01;
GRANT CONNECT,CREATE VIEW,RESOURCE TO DW_DATA;

--DW Prepare Star Cleansing Level tablespace

Create TABLESPACE ts_dw_str_cls_01
DATAFILE '/oracle/u02/oradata/NMartinovichdb/db_qpt_dw_str_cls_01.dat'
SIZE 150M reuse
 AUTOEXTEND ON NEXT 50M
 SEGMENT SPACE MANAGEMENT AUTO;
 
--DW Prepare Star Cleansing Level user

 CREATE USER SAL_DW_CL
IDENTIFIED BY "%PWD%" 
DEFAULT TABLESPACE ts_dw_str_cls_01;
GRANT CONNECT,CREATE VIEW,RESOURCE TO SAL_DW_CL;

--DW StarCleansing Level tablespace

Create TABLESPACE ts_sal_cl_01
DATAFILE '/oracle/u02/oradata/NMartinovichdb/db_qpt_sal_cl_01.dat'
SIZE 150M reuse
 AUTOEXTEND ON NEXT 50M
 SEGMENT SPACE MANAGEMENT AUTO;
 
--DW StarCleansing Level user

 CREATE USER SAL_CL
IDENTIFIED BY "%PWD%" 
DEFAULT TABLESPACE ts_sal_cl_01;
GRANT CONNECT,CREATE VIEW,RESOURCE TO SAL_CL;

--STAR LEVEL tablespaces

Create TABLESPACE ts_sa_fct_balances_01
DATAFILE '/oracle/u02/oradata/NMartinovichdb/db_qpt_sa_fct_balances_01.dat'
SIZE 150M reuse
 AUTOEXTEND ON NEXT 10M
 SEGMENT SPACE MANAGEMENT AUTO;
 
 Create TABLESPACE ts_sa_fct_sales_01
DATAFILE '/oracle/u02/oradata/NMartinovichdb/db_qpt_sa_fct_sales_01.dat'
SIZE 150M reuse
 AUTOEXTEND ON NEXT 10M
 SEGMENT SPACE MANAGEMENT AUTO;
 
 Create TABLESPACE ts_sa_dim_store_01
DATAFILE '/oracle/u02/oradata/NMartinovichdb/db_qpt_sa_dim_store_01.dat'
SIZE 150M reuse
 AUTOEXTEND ON NEXT 10M
 SEGMENT SPACE MANAGEMENT AUTO;
 
 Create TABLESPACE ts_sa_dim_emp_01
DATAFILE '/oracle/u02/oradata/NMartinovichdb/db_qpt_sa_dim_emp_01.dat'
SIZE 150M reuse
 AUTOEXTEND ON NEXT 10M
 SEGMENT SPACE MANAGEMENT AUTO;
 
 Create TABLESPACE ts_sa_dim_cust_01
DATAFILE '/oracle/u02/oradata/NMartinovichdb/db_qpt_sa_dim_cust_01.dat'
SIZE 150M reuse
 AUTOEXTEND ON NEXT 10M
 SEGMENT SPACE MANAGEMENT AUTO;
 
 Create TABLESPACE ts_sa_dim_prod_01
DATAFILE '/oracle/u02/oradata/NMartinovichdb/db_qpt_sa_dim_prod_01.dat'
SIZE 150M reuse
 AUTOEXTEND ON NEXT 10M
 SEGMENT SPACE MANAGEMENT AUTO;
 
 Create TABLESPACE ts_sa_dim_prom_01
DATAFILE '/oracle/u02/oradata/NMartinovichdb/db_qpt_sa_dim_prom_01.dat'
SIZE 150M reuse
 AUTOEXTEND ON NEXT 10M
 SEGMENT SPACE MANAGEMENT AUTO;
 
 --STAR LEVEL users
 
  CREATE USER DM_PRODUCT_BALANCES
IDENTIFIED BY "%PWD%" 
DEFAULT TABLESPACE ts_SA_FCT_BALANCES_01;
GRANT CONNECT,CREATE VIEW,RESOURCE TO DM_PRODUCT_BALANCES;

  CREATE USER DM_RETAIL_SALES
IDENTIFIED BY "%PWD%" 
DEFAULT TABLESPACE ts_SA_FCT_SALES_01;
GRANT CONNECT,CREATE VIEW,RESOURCE TO DM_RETAIL_SALES;

  CREATE USER DM_STORES
IDENTIFIED BY "%PWD%" 
DEFAULT TABLESPACE ts_SA_DIM_STORE_01;
GRANT CONNECT,CREATE VIEW,RESOURCE TO DM_STORES;

  CREATE USER DM_EMPLOYEES
IDENTIFIED BY "%PWD%" 
DEFAULT TABLESPACE ts_SA_DIM_EMP_01;
GRANT CONNECT,CREATE VIEW,RESOURCE TO DM_EMPLOYEES;

  CREATE USER DM_CUSTOMERS
IDENTIFIED BY "%PWD%" 
DEFAULT TABLESPACE ts_SA_DIM_CUST_01;
GRANT CONNECT,CREATE VIEW,RESOURCE TO DM_CUSTOMERS;

  CREATE USER DM_PRODUCTS
IDENTIFIED BY "%PWD%" 
DEFAULT TABLESPACE ts_SA_DIM_PROD_01;
GRANT CONNECT,CREATE VIEW,RESOURCE TO DM_PRODUCTS;

  CREATE USER DM_PROMOTION
IDENTIFIED BY "%PWD%" 
DEFAULT TABLESPACE ts_SA_DIM_PROM_01;
GRANT CONNECT,CREATE VIEW,RESOURCE TO DM_PROMOTION;

--drop users
DROP USER SA_CUSTOMERS;
DROP USER SA_EMPLOYEES;
DROP USER SA_PRODUCTS;
DROP USER DW_CL;
DROP USER DW_DATA;
DROP USER SAL_DW_CL;
DROP USER SAL_CL;
DROP USER DM_PRODUCT_BALANCES;
DROP USER DM_RETAIL_SALES;
DROP USER DM_STORES;
DROP USER DM_EMPLOYEES;
DROP USER DM_CUSTOMERS;
DROP USER DM_PRODUCTS;
DROP USER DM_PROMOTION;

DROP TABLESPACE ts_sa_customers_data_01 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
DROP TABLESPACE ts_sa_employees_data_01 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
DROP TABLESPACE ts_sa_products_data_01 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
DROP TABLESPACE ts_DW_CL_01 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
DROP TABLESPACE ts_DW_DATA_01 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
DROP TABLESPACE ts_DW_STR_CLS_01 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
DROP TABLESPACE ts_SAL_CL_01 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
DROP TABLESPACE ts_SA_FCT_BALANCES_01 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
DROP TABLESPACE ts_SA_FCT_SALES_01 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
DROP TABLESPACE ts_SA_DIM_STORE_01 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
DROP TABLESPACE ts_SA_DIM_EMP_01 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
DROP TABLESPACE ts_SA_DIM_CUST_01 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
DROP TABLESPACE ts_SA_DIM_PROD_01 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
DROP TABLESPACE ts_SA_DIM_PROM_01 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;


